#!/usr/bin/env bash

# .ssh/configがなくて.sshディレクトリがなければ作って、中身のシンボリックリンクを張る
if [ ! -h $HOME/.ssh/config.local ]; then
    [ ! -d $HOME/.ssh ] && mkdir $HOME/.ssh
    [ ! -h $HOME/.ssh/config.global ] && ln -s $DOTFILES/ssh/config.global $HOME/.ssh/config.global
    touch $HOME/.ssh/config.lobal
fi

[ -h $HOME/.ssh/config ] && rm $HOME/.ssh/config
