#!/usr/bin/env bash

# .ssh/configがなくて.sshディレクトリがなければ作って、中身のシンボリックリンクを張る
if [ ! -h $HOME/.ssh/config ]; then
    [ ! -d $HOME/.ssh ] && mkdir $HOME/.ssh
    ln -s $DOTFILES/ssh/config $HOME/.ssh/config
fi