#!/usr/bin/env bash

# .hgrcと.hgignoreと.hgattributeがそれぞれなければシンボリックリンクを張る
[ ! -h $HOME/.hgrc ] && ln -s $DOTFILES/mercurial/hgrc $HOME/.hgrc
#[ ! -h $HOME/.hgignore ] && ln -s $DOTFILES/mercurial/hgignore $HOME/.hgignore

# 環境依存の.zshrcがなければファイルを作ってシンボリックリンクを張る
#[ ! -f $DOTFILES/mercurial/hgrc.$MACHINE ] && cp $DOTFILES/mercurial/hgrc.local $DOTFILES/mercurial/hgrc.$MACHINE
#[ ! -h $HOME/.hgrc.local ] && ln -s $DOTFILES/mercurial/hgrc.$MACHINE $HOME/.hgrc.local
