#!/usr/bin/env bash

# .gitconfigと.gitignoreと.gitattributeがそれぞれなければシンボリックリンクを張る
[ ! -h $HOME/.tool-versions ] && ln -s $DOTFILES/asdf/tool-versions $HOME/.tool-versions
[ ! -h $HOME/.asdfrc ] && ln -s $DOTFILES/asdf/asdfrc $HOME/.asdfrc

